### ISSUE TITLE
URI parsing should reject invalid fields.

### ISSUE THREAD

**Issue by mikeb01** [real-logic/Aeron#130]
URIs containing fields that are unknown should be reject, resulting in an exception.

**Comment by strangelydim** [comment]
For forward-compatibility, it might be nicer to warn-and-continue, and just ignore the parts of the URL that aren't understood.

On the other hand, you might have the opposite opinion, that a newer option given to an old version that doesn't understand it really should be a hard failure.

Opinions?

**Comment by jessefugitt** [comment]
A related comment is that for convenience I have several cases where I'm loading an Aeron channel/stream as a single string (like as the value in a Java properties file) and I've been using the form:
```
key=aeron:udp?remote=127.0.0.1:40123|streamId=10
```

as input to the function:
```
public static AeronUri parse(CharSequence cs)
```

Currently, the AeronUri class can parse the value and it stores the streamId as a key into its custom map.  I still have to manually use that value when I create a publication/subscription but it is handy that Aeron can do the parsing for me at the moment and store the streamId (or whatever other custom fields I needed).  Actually, it would be nice if there was a constructor for publications/subscriptions that could take an AeronUri or some single string value rather than the string/int combination but even without that enhancement, I still find there is some value in the AeronUri having support to parse a streamId (either with the current custom fields implementation or with an explicit field if we go the route of rejecting unknown fields).

**Comment by tmontgomery** [comment]
With the change to #128 the need to reject is less. I see the value of allowing the unknown fields to exist. And now, they shouldn't matter if they do.

@mikeb01 what is your opinion? As a user would it be more convenient to reject? or just ignore?

**Comment by tmontgomery** [comment]
After careful thought, I don't think we should reject with unknown fields. Mostly for back/forward compatibility. But also for the fact that fields might be useful to the applications.
