### ISSUE TITLE
StatsDriver Tool does not use unique directory name when specified

### ISSUE THREAD

**Issue by antrongladney** [real-logic/Aeron#131]
StatsDriver Tool does not use unique directory name when specified on the command line

**Comment by johnpr01** [comment]
This actually has nothing to do with not being able to use unique directory names (which it can't). The issue with this tool is that the LABEL_SIZE was changed from 1024 to 128 in the CountersManager. I have modified the source to use the LABEL_SIZE from CountersManager directly so that this will not happen again. I will be issuing a pull request with this fix.

**Comment by johnpr01** [comment]
Sorry, in the previous comment I meant to say (which it can) instead of (which it can't).
