### ISSUE TITLE
NameResolver causes the media driver to timeout

### ISSUE THREAD

**Issue by WorkingChen** [real-logic/aeron#1367]
When the network fails, the method(InetAddress.getByName(hostname)) returns after tens of seconds，and media driver will timeout。

How should this situation be resolved?

![image](https://user-images.githubusercontent.com/13658946/194756993-58d5d48a-a82a-43c3-9cd8-3dc373edcbf6.png)

**Comment by mikeb01** [comment]
Doing background/asynchronous name resolution is a feature that we have considered for a while, but has yet to become top priority (contact Aeron sales if sponsoring such a feature is of interest to you).

Otherwise some options:
- Look at Aeron driver naming (MediaDriver.Context.resolverInterface & MediaDriver.Context.resolverInterface).  This is a gossip-like protocol that allows for the drivers to each have a name an communicate that between the nodes.
- Add the names to the local hosts file.
- Use IP addresses
- Use a local caching name server on each node.
- Write a custom name resolver.
