### ISSUE TITLE
Slow Receiver doesn't disconnect and reconnect when it falls behind due to flow control

### ISSUE THREAD

**Issue by mst4** [real-logic/Aeron#138]
The Goal of the test is to verify the behavior of a slow subscriber (i.e. a subscriber which falls behind during message consumption)

Setup: Two subscribers and a publisher are running on 3 different machines
-Start 3 mediadrivers on the 3 different machines using the following command
java -cp tools.jar -Daeron.dir=/dev/shm/ag/aeron uk.co.real_logic.aeron.tools.MediaDriverTool
-Start subscriber 1 on machine 2 using the following command
java -cp tools.jar -Daeron.dir=/dev/shm/ag/aeron uk.co.real_logic.aeron.tools.SubscriberTool -c 'aeron:udp?address=192.168.14.38|group=224.17.17.13:32511#5'
-Start subscriber 2 on machine 3 using the following command which specified a rate of consumption
java -cp tools.jar -Daeron.dir=/dev/shm/ag/aeron uk.co.real_logic.aeron.tools.SubscriberTool -c 'aeron:udp?address=192.168.14.34|group=224.17.17.13:32511#5' -r 10mps
-Start the publisher on machine 1 using the following command which specified a rate of sending which is faster than the rate of consumption of subscriber 2
java -cp tools.jar -Daeron.dir=/dev/shm/ag/aeron uk.co.real_logic.aeron.tools.PublisherTool -c 'aeron:udp?address=192.168.14.31|group=224.17.17.13:32511#5' -r 100000m@30mps
-Also start the StatsDriver on machine 3 using the command
java -cp tools.jar -Daeron.dir=/dev/shm/ag/aeron uk.co.real_logic.aeron.tools.StatsDriver

Results: 
The statsDriver reports 300 flow control over runs and after ~1.57 sec subscriber 2 disconnects.
INACTIVE CONNECTION: channel "aeron:udp?address=192.168.14.34|group=224.17.17.13:32511", stream 5, session -392702408

It reconnects and appears to start receiving messages from the live stream ~1.11 sec later..

NEW CONNECTION: channel "aeron:udp?address=192.168.14.34|group=224.17.17.13:32511", stream 5, session -392702408
Channel aeron:udp?address=192.168.14.34|group=224.17.17.13:32511:5[-392702408]: Verifiable message stream received sequence number 5868, but was expecting 1179. Possibly missed 4689 messages.

Subscriber 1 is not affected.
The behavior appears to be correct.

But.. This doesn't happen every time. Sometimes the slow receiver (Receiver2) will just stop receiving messages and that is all that will happen.  The connection will not timeout and the publisher just continues on sending to the receiver that is keeping up with the stream. 

This seems to happen more often at higher rates.  If you change the above rates from sending 30 and receiving 10 messages per second, to 400 kbps sending and 100 kbps receiving the receiver should just stop receiving messages after its buffer has been filled.  

NEW CONNECTION: channel "udp://224.10.10.25:31111", stream 1, session -1122697812
1.000001: 391.000 msgs/sec 100.1 Kbps
1.000016: 390.994 msgs/sec 100.1 Kbps
0.999986: 390.006 msgs/sec 99.8 Kbps
0.999997: 391.001 msgs/sec 100.1 Kbps
1.000003: 222.999 msgs/sec 57.1 Kbps
0.999999: 0.000 msgs/sec 0 bps
0.999998: 0.000 msgs/sec 0 bps
1.000000: 0.000 msgs/sec 0 bps
1.000002: 0.000 msgs/sec 0 bps
0.999999: 0.000 msgs/sec 0 bps
0.999999: 0.000 msgs/sec 0 bps
1.000000: 0.000 msgs/sec 0 bps
1.000000: 0.000 msgs/sec 0 bps

**Comment by tmontgomery** [comment]
I'll be looking at flow control strategies after C++ API is complete.

**Comment by tmontgomery** [comment]
I've been playing with this on a single machine. Here are the command lines for running it with 3 embedded drivers. Must have the latest changes to SubscriberTool for setting the control channel port.

`java -cp aeron-tools/build/libs/tools.jar -Daeron.dir=$TMPDIR/aeron-sub1 -Daeron.tools.controlChannelPort=62778 uk.co.real_logic.aeron.tools.SubscriberTool --driver embedded -c 'aeron:udp?interface=127.0.0.1|group=224.17.17.13:32511#5'`

`java -cp aeron-tools/build/libs/tools.jar -Daeron.dir=$TMPDIR/aeron-sub2 -Daeron.event.log="CMD_OUT_IMAGE_READY,REMOVE_IMAGE_CLEANUP,CMD_OUT_ON_INACTIVE_IMAGE,CMD_IN_ADD_SUBSCRIPTION,CMD_OUT_ON_OPERATION_SUCCESS" uk.co.real_logic.aeron.tools.SubscriberTool --driver embedded -c 'aeron:udp?interface=127.0.0.1|group=224.17.17.13:32511#5' -r 10mps`

`java -cp aeron-tools/build/libs/tools.jar -Daeron.dir=$TMPDIR/aeron-pub uk.co.real_logic.aeron.tools.PublisherTool --driver embedded -c 'aeron:udp?interface=127.0.0.1|group=224.17.17.13:32511#5' -r 100000m@30mps -s 1000`

For me, this is behaving well. However, I do see a potential issue that I will drill down into soon. I don't think it explains what you observed, though.

Since the issue was filed, we made some changes that could effect what was seen. So, it could be OK now. However, I will keep this open until I can fully understand the potential issue I see is.

**Comment by tmontgomery** [comment]
The potential issue has been dealt with via a cooldown added with 6fa50af . This seems to work as expected now with a long run.
