### ISSUE TITLE
Should a slow subscriber affect other subscribers on the same stream on the same media driver?

### ISSUE THREAD

**Issue by mst4** [real-logic/Aeron#139]
Setup:  A publisher on Machine 1 sending to Two Subscribers sharing a media driver on Machine 2
-Start MediaDrivers on Machines 1 and 2 using the following command
```java -cp tools.jar -Daeron.dir=/dev/shm/ag/aeron uk.co.real_logic.aeron.tools.MediaDriverTool```

-Start subscriber 1 on Machine 2 using the following command
```java -cp tools.jar -Daeron.dir=/dev/shm/ag/aeron uk.co.real_logic.aeron.tools.SubscriberTool -c 'aeron:udp?address=192.168.14.34|group=224.17.17.13:32511#5'```

-Start subscriber 2 on Machine 2 using the following command which specified a rate of consumption
```java -cp tools.jar -Daeron.dir=/dev/shm/ag/aeron uk.co.real_logic.aeron.tools.SubscriberTool -c 'aeron:udp?address=192.168.14.34|group=224.17.17.13:32511#5' -r 10mps```

-Started publisher on Machine 1 using the following command which specified a rate of sending which is faster than the rate of consumption of Subscriber 2
```java -cp tools.jar -Daeron.dir=/dev/shm/ag/aeron uk.co.real_logic.aeron.tools.PublisherTool -c 'aeron:udp?address=192.168.14.31|group=224.17.17.13:32511#5' -r 100000m@30mps```

Results:
Subscriber which is keeping up (subscriber 1) slows down. It receives msgs in
bursts.No loss is reported and subscriber 2 continues to receive messages at the configured rate of 10msgs/sec.
Expected the slow subscriber (subscriber 2) to disconnect and reconnect and start receiving msgs from the live stream just as it did in the aforementioned scenario.

Question: Is this correct? Shouldn't the behavior be the same for a slow subscriber sharing a media driver as a slow subscriber which is NOT sharing a media driver (case explained [here](https://github.com/real-logic/Aeron/issues/138))?

**Comment by tmontgomery** [comment]
I'll be looking at flow control strategies after C++ API is complete.

**Comment by tmontgomery** [comment]
This is acting as expected. The answer is that 2 Subscriptions sharing a media driver should act differently than 2 Subscriptions with 2 media drivers. When sharing a media driver, the observed behavior in this issue is the correct behavior.

The reasoning has to do with the media driver being the agent of flow control information. This is so that multiple Subscriptions can share the same resources. i.e. a unicast channel or the same multicast channel. So, no matter how many Subscriptions use the same Image (sessionId, channel, and streamId), the flow control sent back to the Publication is aggregated by the media driver.

If this behavior is not desired, then multiple media drivers should be used.
