### ISSUE TITLE
[AeronArchive] Allow disabling UDP aeron.archive.control.response.channel 

### ISSUE THREAD

**Issue by StephanDollberg** [real-logic/aeron#1416]
Hi,

The defaul value for `aeron.archive.control.response.channel` creates a localhost subscription. This is in addition to an `aeron:ipc` one that is also created by default.

Equally it doesn't seem to be possible to disable the UDP channel altogether. Set `aeron.archive.control.response.channel` to something non-udpish makes it error out.

This is an issue because a localhost socket can't be accelerated by most kernel bypass LD_PRELOAD solutions which in turn means that the default forces the Aeron receive thread to poll the system even if kernel bypassed.

My understanding of aeron archive might be lacking but I don't understand why you'd want a localhost subscription in addition to an `ipc` one anyway.

**Comment by mikeb01** [comment]
I think you are looking at an older version.  The latest release removes the default, requiring it to be set.  Because, as you mention, a default of localhost does not make a lot of sense.  However, it does need to be set, but I can see the value of an IPC-only archive configuration so that the UDP publication and subscription resources are not created.  I think this should be an explicit setup/configuration option.  When archive is used with cluster there are cases where remote access between archives is required, so defaulting it to IPC-only could break for some people.

**Comment by StephanDollberg** [comment]
> The latest release removes the default, requiring it to be set.

I see, https://github.com/real-logic/aeron/wiki/Configuration-Options#aeron-archive-client-options probably needs some updating to reflect that.

 > but I can see the value of an IPC-only archive configuration so that the UDP publication and subscription resources are not created

Yep, that's what I am asking for :)
