### ISSUE TITLE
Aeron Current Performance

### ISSUE THREAD

**Issue by amit2103** [real-logic/Aeron#142]
Hi,

I heard Martin's talk about Aeron . I am trying out Aeron for sometime and trying to build some apps with it.

Can you let me know what are the pros of Aeron vs ZeroMQ or Nanomsg.
It seems to me that Aeron has some cleaner design architecture and also since we are a Java shop its easier for us to understand the code.

However unicast and multicast are both supported by ZeroMq and Nanaomsg. What are the pros of Aeron vs these products and also commercial ones like Informatica?

**Comment by mjpt777** [comment]
Aeron is aiming to be the scalpel, rather than the multitool, of messaging that focuses on being a pure streaming message transport. Other services may in time be built on top of it but should never pollute or encumber the core.

Compared to other products you will have to judge for yourself and if it meets your needs. From my perspective the focus of Aeron is simplicity and outright performance.
