### ISSUE TITLE
IPC semantics and changes to Publication Session ID

### ISSUE THREAD

**Issue by tmontgomery** [real-logic/Aeron#150]
Martin and I have discussed the semantics of IPC and wanted to capture our thoughts as we implement and refine the idea(s).

Currently, Aeron has a single type of Subscription and Publication. One that sends to a channel and Stream ID (for Publication, also a Session ID). However, this doesn't capture the entire needs of applications. Specifically, applications that want to have high performance connectivity _only_ to other components on the same box (or over RDMA to other boxes).

The choice of how best to connect some components often shouldn't be left to the transport (or messaging system), but should be an explicit architectural choice. To that end, there should be a set of choices that require the application developer to choose the correct mechanism based on purpose and scope. But should allow the same data delivery mechanisms to be used.

Different types of Publications:

1. Publish to a Channel & Stream ID for any subscriber on or off media driver (normal publisher)
1. Publish to a Stream ID for any subscriber on the same media driver (IPC publisher) (__NOTE: does not go out to the network__)

Different types of Subscriptions:

1. Subscribe to a Channel & Stream ID pair for any publisher on or off media driver (normal subscriber)
1. Subscribe to a Stream ID for any IPC publisher on the same media driver (IPC subscriber) (__NOTE: does not listen to any Publication external to the media driver__)
1. Subscribe to a Channel & Stream ID for any publisher on the same media driver ("Spying" on a normal publisher for purposes such as local processing, archival, etc.)

_Net-Net_: Adding an "IPC-only" namespace for Publications and Subscriptions. Plus adding the ability for a special Subscription to subscribe to a specific local-to-the-media-driver Publication (called a "Spy").

We believe this encapsulates the various use cases as well as maintains crucial architectural decisions that would be a mistake to hide or not expose to the application.

API Changes

- [x] Session ID will be assigned by the media driver for a Publication and will __not__ need to be assigned by the application. Each Publication using the same Channel and Stream ID pair will use the same media driver logbuffer.
- [x] Addition of methods to create Publications and Subscriptions for IPC entities under an IPC only channel space (a constant channel string):
    - [x] `Aeron.addSubscription(IPC_CHANNEL, StreamID)`
    - [x] `Aeron.addPublication(IPC_CHANNEL, StreamID)`
- [ ] Addition of methods to create "Spy" Subscriptions for specific Publications, `Aeron.addSpy(Channel, StreamID)`. This is a Subscription object and can be polled as normal and uses same semantics for data delivery as other Subscriptions.

**Comment by RichardWarburton** [comment]
Semantically I think these changes all sound great.

However I think we should think about the use of Aeron as a tool that decouples producers and consumers from the underlying mechanism as much as possible. I would like to be able to write an application (for example the project I'm currently working on) where I can reconfigure my application to use IPC or Unicast Aeron streams as appropriate.

If the `Aeron.addSubscription(Channel, streamID)` method also allows me to use IPC by using a channel string such as "ipc" then the API becomes more flexible. My application built on top of Aeron can just set a property to be the channel and I can put in "ipc" if I want. This still makes the choice explicit, but lets end users defer that choice to the startup of their application rather than at compile time. It also lets users more easily benchmark IPC vs UDP based streams and then make the architectural choice based upon that data.

It also wouldn't preclude offering a `Aeron.addSubscription(StreamID)` and `Aeron.addPublication(StreamID)` overloads which are more fluent and just delegate to passing in "ipc" as a parameter.

There might be other ways API-wise to do it and I'm not attached to that API necessarily but I think whatever API is picked we should try and make switching between IPC and UDP based streams as painless an operation as possible.

Does that make sense?

**Comment by mjpt777** [comment]
@RichardWarburton Those points make very good sense to me. If we go that way we should add an IPC constant to the client library that documents the usage.

**Comment by tmontgomery** [comment]
I've updated the initial issue to include the constant channel namespace for IPC. The string should follow the Aeron URI scheme. Probably `aeron:ipc`.

**Comment by tmontgomery** [comment]
42fda59e093493893e6d96418f50b9459f6327e3 has removed SessionID as a parameter of `Aeron.addPublication` and as of this commit, the driver has responsibility for SessionID generation as mentioned above.

**Comment by tmontgomery** [comment]
The semantics with IPC have been added. The channel is `aeron:ipc`. Should be fully usable now.

Semantics are slightly different than network channels.
- an `addSubscription` will create the Image if not already created and an `onAvailableImage` will always be triggered. This notification says nothing about the `Publication`. An Image can exist with IPC without an active `Publication`.
- the Image exists as long as there are either `Subscription`s or `Publication`s alive. Once all are gone, the Image will be reclaimed. As the application must have closed the `Subscription`s and `Publication`s previous to the image going away (or timedout), there really is no `onUnavailableImage` delivery to the application.

**Comment by ohpauleez** [comment]
Is there any sense when this will land on an official release?

**Comment by mjpt777** [comment]
It is in the current release but we would not recommend using it until the next release we put out. I've found a couple of bugs in the current release with it plus it needs optimising. 

It should be good to go within a month.

**Comment by ohpauleez** [comment]
Awesome - thanks a ton.  Feel free to reach out if there's anyway I can help.
