### ISSUE TITLE
CLI target

### ISSUE THREAD

**Issue by sirinath** [real-logic/Aeron#156]
Is it possible to have a CLI version also like SBE.

**Comment by mjpt777** [comment]
Sure if you'd like to submit a PR we would welcome that. Are you able to put the effort in?

**Comment by sirinath** [comment]
I don't think I am the best person to do the PR.

**Comment by mjpt777** [comment]
We don't have the time on our side to do it unless someone wanted to sponsor the development.

The various things you have asked for are significant development rather than simple features. They are not likely to happen unless someone has a reason to do them. What work we do we are willing to share but our time is limited.

**Comment by RichardWarburton** [comment]
Can you clarify what you mean by a "CLI" version?

**Comment by sirinath** [comment]
A .net version so you can communicated with clients written in a .net language. It should have read as "CIL"

**Comment by sirinath** [comment]
Basically run VS C++ to generate CIL/CLI/CLR/.Net target using /clr:safe option fixing the performance regression (this is the hard part) which is your strong suite. Perhaps you can publish on NuGet also one are recreations are fixed.
