### ISSUE TITLE
AeronCluster.java decoding order issue

### ISSUE THREAD

**Issue by ssh352** [real-logic/aeron#1580]
<img width="790" alt="Screenshot 2024-04-02 at 11 06 20 PM" src="https://github.com/real-logic/aeron/assets/41779116/4558fb80-9685-45af-9422-2f5a473ca9ef">

In general, sbe field decoding should follow xml declaration order.  However clusterSessionId is decoded before leadershipTermId.

Please advise. Thanks!

**Comment by vyazelenko** [comment]
@ssh352 Fields within a fixed block can be accessed in any order since they all have fixed offset. The order of access matters when accessing variable length fields and repeating groups.

**Comment by ssh352** [comment]
@vyazelenko  It is probably not a big deal here. But even for fixed size field it is advised (I understand it is ok) to decode in schema order. Thanks!

https://github.com/real-logic/simple-binary-encoding/wiki/Design-Principles#streaming-access

```
The SBE codecs are designed to encode and decode messages based on a forward progression of the position in the underlying buffer. It is possible to backtrack to a degree within messages but this is highly discouraged from a performance and latency perspective.
```

**Comment by vyazelenko** [comment]
Since [SBE 1.30.0](https://github.com/real-logic/simple-binary-encoding/releases/tag/1.30.0) it is possible to enable runtime checks that will enforce access order.
There is no issues with the above code as the messages are the leadership messages are not going to be frequent and the fixed fields are likely to be in the same cache line anyway.
