### ISSUE TITLE
C++ API Deprecation

### ISSUE THREAD

**Issue by callmerockett** [real-logic/aeron#1678]
Hi,

In [Release Note for version 1.45.0](https://github.com/real-logic/aeron/releases?page=2#:~:text=Aeron%20currently%20has%20two%20C%2B%2B%20APIs%2C%20a%20pure%20C%2B%2B%20version%20and%20a%20wrapper%20over%20the%20C%20API.%20This%20release%20we%20are%20no%20longer%20adding%20new%20features%20to%20the%20C%2B%2B%20API.) we had this statement:

> Aeron currently has two C++ APIs, a pure C++ version and a wrapper over the C API. This release we are no longer adding new features to the C++ API.

Some questions about it:
1. Why? 
2. Only pure C++ version API will be deprecated or both of them?
3. What about later releases?

**Comment by mikeb01** [comment]
1.  Reduce the maintenance cost.  We currently have three implementations of the Aeron client.  When we need to make client changes they need to happen in all three places independently.  This will reduce it to two.  Also adding support for other languages like Python and Rust is easiest as a layer over C rather than an independent implementation or wrapping C++.

2.  Only the pure C++ will be deprecated in favour of the C++ wrapper over the C API.

3.  I'm not sure what you mean about later releases.  Eventually we will remove the pure C++ API.

**Comment by callmerockett** [comment]
Thank you for the reply!
