### ISSUE TITLE
Question - Aeron Releases support

### ISSUE THREAD

**Issue by callmerockett** [real-logic/aeron#1680]
Which Aeron older releases still got fixes? Any recommendation about migrating from older versions?

**Comment by mikeb01** [comment]
We typically only apply patches to the latest release.  However, at the moment, we are patching 1.44.x and 1.46.x as 1.44.x is the last release that will support JDK8.  However, we won't continue fixes for 1.44.x indefinitely.

**Comment by vyazelenko** [comment]
@callmerockett For people on commercial support we support old versions up to 1 year back. Since our release cadence is once a quarter it is roughly 4 latest major releases that are supported. 

A recommendation is to always update to the latest Aeron release as it will contain the latest fixes and improvements.

**Comment by callmerockett** [comment]
Thank you for the reply!
