### ISSUE TITLE
Response channel: publication re-establishment fails with C media driver

### ISSUE THREAD

**Issue by george-xm** [real-logic/aeron#1686]
When using response channels experimental feature and the server-side process restarts, the response publication is not re-established back to client's subscription.

Steps to reproduce:
- Start C media driver with -Daeron.enable.experimental.features=true
- Run response_server with default parameters (from aeron-samples\src\main\c\response)
- Run response_client with default parameters (from aeron-samples\src\main\c\response)
- Wait a few seconds and notice server is receiving & offering back messages
- Stop & restart response_server while response_client keeps running

What happens:
- Client re-establishes outgoing connection & server receives message
- Server successfully creates response channel publication (aeron_async_add_publication / aeron_async_add_publication_poll succeeds)
- Server's response channel publication is not connected to client's subscription and server prints: "Offer failed because publisher is not connected to a subscriber"

Is this by design? And if so, what do you suggest to fully re-establish the connection? The only I can think is for the client process to detect the disconnection using some kind of application-level keep-alive and then re-create its publication/subscription pair.

Any suggestions welcome, thanks in advance.

**Comment by george-xm** [comment]
Short update: tested the same scenario using response_server/response_client (build from C source code) but using Java media driver running on a standalone process and it works as expected.  So, it seems like a bug/missing feature in C media driver.

**Comment by mikeb01** [comment]
In general this isn't really supposed to work, but I think does on occasion due to the way that resources linger.  I managed to get it to work with the C driver by stopping and starting the server very quickly.  I also got it to fail in the Java driver by leaving the server up for longer.  Some more digging is required to determine why there is a difference in timing, but I think that if you see a disconnect or similar on the client side, then the client should reconnect.

**Comment by mikeb01** [comment]
Further investigation, I did find an issue with the response channels code which is fixed now.  We now see the same behaviour between the Java and C drivers.  However, it should not noted that clients should not rely on this.  They should detect server outages and reconnect.  The above scenario only works because the client is shut down abruptly and the driver hasn't had enough time to timeout the client.  Given enough time the response publication's image will go unavailable and it won't automatically recover.

**Comment by george-xm** [comment]
Clear, makes sense what to expect now. Thanks for the help @mikeb01
