### ISSUE TITLE
Question - Joining cluster after member host down

### ISSUE THREAD

**Issue by kchgoh** [real-logic/aeron#1695]
It appears that the feature for dynamic cluster member was removed in version 1.41. So in a normal setup where each cluster node is on a different host, if one cluster host goes down due to some hardware issue (i.e. we cannot bring up the process on the same host within a reasonable amount of time), does that mean it is not possible to bring up the process on a different host to join the cluster to restore the quorum?

**Comment by vyazelenko** [comment]
@kchgoh It is possible if host names (DNS) or driver names are used instead of IP addresses. Just bring another host and use the same DNS name/driver name as the one that has issues. When using DNS names you'll need to update your DNS to point to a different IP address.

See also https://github.com/real-logic/aeron/wiki/Name-Resolution.

**Comment by kchgoh** [comment]
Thanks for the quick reply! From the wiki it will auto resolve the DNS name again on interval so it should be fine for this scenario, good to know that.

The README file may need to be updated as it still mentions the Dynamic Membership feature. Though it would be nice if a similar feature will become available again in the future.

Really appreciate the great work!
