### ISSUE TITLE
Publication offer/tryClaim should return NOT_CONNECTED when flow control full and no SM within a period of time

### ISSUE THREAD

**Issue by postol** [real-logic/Aeron#187]
Hi,

we are trying to implement custom flow control to achieve the semantics that in case all subscribers are gone the offer method of publication will start returning NOT_CONNECTED again instead of continuing successful publishing or back pressure in case the term buffer is full - which will happen pretty soon because there is no subscriber to receive the data anymore.

Based on Todd's recommendation in issue #161 we have implemented the flow control as in the code below but even though we set positionLimit to 0 in onIdle method the offer still return success or back pressure.

Can someone take a look and let us know whether this is bug or just a wrong usage of flow control? In case it is a wrong usage can you provide us a code how to achieve the behavior described above?

Thank you very much in advance.

Kind regards,
Petr

	public class NotConnectedFlowControl implements FlowControl
	{	
		private final int notConnectedTimeout;
		private long positionLimit = 0;
		private int positionBitsToShift;
		private int initialTermId;    
		private long lastStatuMessageTimeStamp;
		
		public NotConnectedFlowControl(int notConnectedTimeout) {
			this.notConnectedTimeout = notConnectedTimeout;
		}

		/**
		 * {@inheritDoc}
		 */
		public long onStatusMessage(
			final int termId, final int termOffset, final int receiverWindowLength, final InetSocketAddress address)
		{    	
			lastStatuMessageTimeStamp = System.currentTimeMillis();
			final long position = computePosition(termId, termOffset, positionBitsToShift, initialTermId);
			final long newPositionLimit = position + receiverWindowLength;
			positionLimit = Math.max(positionLimit, newPositionLimit);
			return positionLimit;
		}

		/**
		 * {@inheritDoc}
		 */
		public void initialize(final int initialTermId, final int termBufferCapacity)
		{    	
			this.initialTermId = initialTermId;
			positionBitsToShift = Long.numberOfTrailingZeros(termBufferCapacity);
			positionLimit = computePosition(initialTermId, 0, positionBitsToShift, initialTermId);
			lastStatuMessageTimeStamp = System.currentTimeMillis();
		}

		/**
		 * {@inheritDoc}
		 */
		public long onIdle(final long now)
		{
			if((System.currentTimeMillis() - lastStatuMessageTimeStamp) > notConnectedTimeout) {    		
				positionLimit = 0;    		
			}
			return positionLimit;
		}
	}

**Comment by tmontgomery** [comment]
Since the suggestion, we've done a few refactorings of the publication logic. Looking quickly, I don't think returning a 0 from a flow control strategy will set the publisherLimit to 0 right now. This is mostly because we reduced the cache traffic between the Conductor and the Sender threads by changing how updating of limit was done and communicated.

@mjpt777 and I will discuss and see if this is something we want to allow and when one of us can get to it to make sure it doesn't regress performance-wise.

**Comment by postol** [comment]
Hi Todd,

thank you for your quick response. Please let me know once you discuss with Martin and what is your conclusion. The thing is that at moment we are basically unable to distinguish between whether the back pressure is caused because of slow consumer(s) which are still connected or because there is no consumer connected anymore. To explain our use case, we have publisher and subscriber, subscriber connects and everything is working fine, then the subscriber disconnects and publisher after a while starts receiving back pressure from offer method becasue the term buffer is full. At that moment we basically don't know what to do - whether we should keep retrying with some sort of timeout or whether we should start discarding the messages and don't wait for timeout (because no one is interested anymore). Other question is in case the subscriber reconnects after a while, let's say one minute - are the messages offered through publication during the disconnection sent to the subscriber or are they discarded?

Sorry if these questions are silly but we just want to understand how exactly this works and whether we are missing something in our design ... I'm pretty sure there is a way to solve this because it seems to me like a standard use case.

Thank you and kind regards,
Petr

**Comment by tmontgomery** [comment]
Soon as we have time to discuss, will get back.

As another option, you could use the strategy you have to fill another counter (you would need to make a file and use the counters manager, but that is quite simple) that the app can use for knowing if the receiver has sent an SM or not within some time. The publisherLimit was a suggestion to perhaps utilize current semantics. The approach can work just by setting a counter that the application can read just as well and removes any changes we happen to make to publisherLimit.

Just IMO, I think the use case mixes couple bits of application logic into the transport where it probably should not be. One is liveness, another is message durability.

Mixing liveness (sender or receiver) into the transport is something I usually avoid.

To take this away from Aeron, let's consider TCP. Imagine a TCP connection becomes half-open. i.e. one side crashes or becomes unreachable. The sender will fill the TCP window (this can happen even in the time it takes for a RST to arrive). Then the sender sees a blocking send, just as if it were flow controlled. TCP, however, may or may not even see a RST in this case to close the connection. It wouldn't in the case of an unreachable, for example. Applications relying on TCP connection state for liveness is a common issue and cause of fragility. Best to make it an application concern instead and build it into the protocols of interaction.

Now Aeron is slightly different in that it does not provide notification of receiver liveness. In my experience, this is a good thing in that it is best to do application liveness and semantics at the application instead of mixing into the transport. The questions of what to do, etc. you mention are best handled by application semantics and not by tying them to transport mechanics.

Another part you mention is whether a receiver should get messages that were sent while it was gone.

Simply stopping sending isn't enough to do this. Knowing what was received (and what wasn't) is a key to this. This is very different than what was sent. So, relying on receiver liveness via SMs doesn't really help here. Just as it doesn't help in TCP.

**Comment by tmontgomery** [comment]
@mjpt777 and I have discussed this at some length. And here is our thoughts.

When `Publication.offer` or `Publication.tryClaim` can NOT succeed, we see a lot value in distinguishing the reason for that. One of the reasons might be that the receivers have all gone away and no SMs have progressed flow control AND the flow control windows have filled up. In this case, the right thing to do is to return `NOT_CONNECTED`. It is not, however, the job of the transport to return `NOT_CONNECTED` if there is room in flow control to place the data. We intend to make this the default operation and to take it out of the realm of the flow control strategy.

What this means is that by default, `NOT_CONNECTED` will be returned if flow control has been filled and the time of the last seen SM has been too long (this will probably be configurable on the client). We also intend to make the time of last SM seen queriable by the `Publication` as a monitoring aid.

If tighter constraints on sending are required, such as knowing prior to flow control being full if there is a live receiver, this should be built into the application protocols of interaction.

The timeline for this change will be sometime in Q1. We intend to get to it fairly quickly.

**Comment by postol** [comment]
Hi Todd,

again thank you for the fast response and even more for the decision you and Martin made - the behavior you just described perfectly suits our needs and is basically what we were looking for. It will make Aeron even better ... btw it is awesome project and thank you and Martin for all the hard work - it is much appreciated.

Looking forward to this and other enhancements in the future.

Petr

**Comment by tmontgomery** [comment]
@postol ah, great! I was somewhat convinced that this wasn't quite what you wanted. So, that is great that it is useful to you.

**Comment by tmontgomery** [comment]
With 3e8b361e0ab1c03ee799df392273a056887146a7 there is now some support for querying the status on a Publication to see if the subscribers are active or not. It is not currently returned by `offer` or `tryClaim`, but when BACK_PRESSURE is returned, it is possible to call `isStillConnected` to see if subscribers are active.

**Comment by postulka** [comment]
Hi Todd,

perfect, we will give it a try. Thanks a lot for the change, much appreciated.

Petr

**Comment by tmontgomery** [comment]
I should amend my statement and say that `isStillConnected` may be called at any time. Not just when `offer`/`tryClaim` fails.

**Comment by tmontgomery** [comment]
With the latest commits, this behavior is now completely in.
