### ISSUE TITLE
Does network bufferbloat slow Aeron? Could CoDel be a useful addition?

### ISSUE THREAD

**Issue by steffenyount** [real-logic/Aeron#285]
"Bufferbloat is the undesirable latency that comes from a router or other network equipment buffering too much data."

I stumbled across the following pretty amazing blog http://blog.cerowrt.org/post/ from a contributor to the https://www.bufferbloat.net/projects/ and was thinking that Aeron is probably hit by similar bufferbloat issues on slower networks with oversized buffers.

Have you seen anything like that in testing?

Is Aeron immune to this problem? If so, why? If not, would it be worth adding a flow control scheme like https://tools.ietf.org/html/draft-ietf-aqm-codel-04 to Aeron to eliminate bufferbloat related performance slowdowns?

**Comment by tmontgomery** [comment]
Bufferbloat effects everything and Aeron is not immune to it.

CoDel is, primarily, a queue management technique for routers (and other edge devices) and doesn't have anything to really do with how flow control is handled in Aeron. So, there really isn't a way to "add it to Aeron" effectively.

**Comment by tmontgomery** [comment]
I did mention "primarily" and "flow control" in my brief message. Sorry for being terse. Allow me to explain in more detail.

Let's not conflate flow control and congestion control. Bufferbloat is best handled by congestion control and not flow control. Aeron does not currently do anything with congestion control. This is due to the original direction of Aeron and its primary operating environments within low latency trading. Quite simply, slowing down due to increasing RTT is undesirable. In fact, even after loss, slow down is less desirable, but necessary for stability.

There is no reason for Aeron __flow control__ to account for bufferbloat since it is the wrong mechanism. Aeron __congestion control__ would be more ideal but does not yet exist.

As we have seen interest in Aeron in other environments, recently a sponsor has stepped up to aid us in developing a few congestion control strategies for Aeron. One will most likely be RTT based and be akin to BBR (once details are known) and attempt to have an effect similar to CoDel from the service time measurement influencing rate adjustment. However, not all desired strategies __must__ rely on RTT. It is likely at least one strategy will rely solely on loss.

**Comment by steffenyount** [comment]
FYI: The BBR paper is available on the ACM queue website: http://queue.acm.org/app/
