### ISSUE TITLE
Image Unavailability Question

### ISSUE THREAD

**Issue by sturgeda** [real-logic/Aeron#310]
Hi. My consumers would like to know quite quickly (1 second) when a stream of data becomes unavailable. I have implemented this using a heartbeat mechanism.. My publisher sends a heartbeat every 300ms and my consumers mark the data stream as stale if there has been no heartbeat for 1 second. This all works fine and well though looking through the Aeron API in more detail I see that there are image (un)availability handlers which could be used to achieve the same purpose. I've tried using an unavailability handler though with the default timeouts, my consumers are notified at least 20 seconds after the data stream becomes unavailable. I then tried modifying the timeouts and came across 'aeron.image.liveness.timeout' which when set to a low value such as 500ms reduced this delay to about 1 second (ish) though at the same time I see the consumer flapping between available/unavailable several times over about a 5 second period after the publisher is stopped which seems odd..

So my questions are (i) is using a heartbeat to detect stream unavailability considered a viable alternative to the image unavailability handler ? (ii) what are the recommended settings/timeouts to achieve image unavailability notification in under 1 second w/o the flapping I mentioned ?

Many Thanks

Dave

**Comment by mjpt777** [comment]
The only reliable means to check for availability is with an application level heartbeat.  One second is a very low value considering all the possible pauses which can happen. If you want a timely close of a stream then send an application level message to indicate the end of the stream.

The Aeron timeouts are transport related. For example, consider a healthy driver at the source but the publishing thread has got blocked for some reason. The subscribers would be getting transport level heartbeats but no indication from the publisher. Concerns have to be applied at the appropriate level to be reliable. Vendors who promise otherwise are misleading or naive.
