### ISSUE TITLE
agrona.com artifact 0.9.4-SNAPSHOT  dependency not present in maven

### ISSUE THREAD

**Issue by rickardpl** [real-logic/Aeron#328]
When cloning aeron from github a missing artifact prevents Aeron to build. Changing to released 0.9.3 gives that object ArrayListUtil is not available, still preventing gradle to build without errors.

**Comment by RichardWarburton** [comment]
The github Aeron build may be a snapshot and may have snapshot dependencies, that is because its under frequent development and improvement.

If you want a stable version of Aeron to use in your application then you should use the latest released version from maven central.

If you want to contribute to aeron then you may need to install the snapshot version of Agrona from github as well.
