### ISSUE TITLE
Two way communication using Aeron

### ISSUE THREAD

**Issue by Hemanth-Eduru** [real-logic/Aeron#358]
I want to build a two way communication ( similar to a client - server ) rough code  for the client which first starts the transmission is like as follows

```
main()
{
    publisher();
}

publisher()
{
    // This has code similar to that of BasicPublisher in aeron-samples
    // except at the end we will call the subscriber
    
    // Code to send some messages
    
    // sending done now call listner
    
    listner();
}

listner()
{
    // This has code similar to that of Basicsubscriber in aeron-samples
    
    // Some additional code to processes received messages
    
    // now call the publisher
    
    publisher();
    
}

```
For the other client  the first will be listener and then reply

```
main()
{
    listner();
}

publisher()
{
   // This has code similar to that of BasicPublisher in aeron-samples
    // except at the end we will call the subscriber
    
    // Code to send some  reply messages
    
    // sending done now call listner
    
    listner();
}

listner()
{
    // This has code similar to that of Basicsubscriber in aeron-samples
    
    // Some additional code to processes received messages
    
    // now call the publisher
    
    publisher();
    
}

```

But it is not working as expected only first few messages are getting transmitted.
Any ideas how to implement a two way messaging system using Aeron?

**Comment by tmontgomery** [comment]
You should look at the Ping/Pong examples to make sure you are retrying appropriately from back pressure on offer/tryClaim, etc.

**Comment by tmontgomery** [comment]
In terms of how to do a request/response system with Aeron, you have some options.

- Use a static back channel that is setup between components in your system. Fairly typical messaging system approach where each request is labeled with a response ID so that multiple requests can be differentiated with ease.

- Use a dynamic back channel where the responder sets up a Publication to send responses back on as needed. Still need a response ID as with a static channel. Only real difference is that the response channel isn't always active.

- Use a dual channel approach where each channel has a response channel and the act of setting up the request must also set up the response channel.

Several users have built request/response systems into their apps. Many different ways to go about it.

Someday, though, we will get time to build a generic method hopefully.

**Comment by Hemanth-Eduru** [comment]
I will see those examples  and will get back here

**Comment by Hemanth-Eduru** [comment]
Now I was able to Implement the 2 way communication system, but once the messages (total size) reaches near to that of allocated log buffer size the speed of send and receive drastically slowed down (Initially I was able to send and receive  >1 Lakh messages per-sec (using busy spin idle strategy and around 1K messages in SleepingIdleStrategy (my code is in C++)) later the rate is not even touching 1 message per second  any ideas what could be causing this delay ?

I am Sending using IPC and Sending on one stream ID and receiving on another stream ID

**Comment by mjpt777** [comment]
Is this OK to close now?

**Comment by Hemanth-Eduru** [comment]
Yup I think we can close this issue now and i am closing this
