### ISSUE TITLE
Ping/Pong sample same channel, different streams

### ISSUE THREAD

**Issue by dasch-dk** [real-logic/aeron#372]
Hi,

What I am trying to do (don't know if this is even possible) is to do two-communication on the same channel but use different streams. Further, this is across two machines hence I am using embedded media driver on each.

I am trying to run:
**On Host1 - 10.20.30.19 - Pong**
java -cp '*' -Daeron.sample.embeddedMediaDriver=true -Daeron.sample.info=true -Daeron.sample.ping.channel="aeron:udp?endpoint=10.20.30.19:7211" -Daeron.sample.pong.channel="aeron:udp?endpoint=10.20.30.19:7211" -Daeron.sample.pong.streamId=11 io.aeron.samples.Pong

**On Host2 - 10.20.30.20 - Ping**
java -cp '*' -Daeron.sample.embeddedMediaDriver=true -Daeron.sample.info=true -Daeron.sample.ping.channel="aeron:udp?endpoint=10.20.30.19:7211" -Daeron.sample.pong.channel="aeron:udp?endpoint=10.20.30.19:7211" -Daeron.sample.pong.streamId=11 io.aeron.samples.Ping

On Host1 I see the available image
Available image on aeron:udp?endpoint=10.20.30.19:7211 streamId=10 sessionId=-494496036 from 10.20.30.20:57724

So the Ping'er subscribes to Pong, but Pong doesn't seem to subscribe to Ping.

I have also, tried using IP in the channel but different ports for ping and pong with the same result as above.

**Can you please help explain what happens here? Should this even work? If not why not?**

Note that the below (different IPs for ping/pong) works just fine.

**On Host1 - 10.20.30.19 - Pong**
java -cp '*' -Daeron.sample.embeddedMediaDriver=true -Daeron.sample.info=true -Daeron.sample.ping.channel="aeron:udp?endpoint=10.20.30.20:7212" -Daeron.sample.pong.channel="aeron:udp?endpoint=10.20.30.19:7211" -Daeron.sample.warmup.messages=10000 io.aeron.samples.Ping

**On Host2 - 10.20.30.20 - Ping**
java -cp '*' -Daeron.sample.embeddedMediaDriver=true -Daeron.sample.info=true -Daeron.sample.ping.channel="aeron:udp?endpoint=10.20.30.20:7212" -Daeron.sample.pong.channel="aeron:udp?endpoint=10.20.30.19:7211" -Daeron.sample.warmup.messages=10000 io.aeron.samples.Pong

Thanks a lot in advance!

**Comment by tmontgomery** [comment]
Host2 is a subscriber to ping channel and a publisher to pong channel. Host1 is a subscriber to pong channel and a publisher to ping channel. Subscribers can only subscribe to a local IP.

That is why the second configuration works and the first does not.

If you look in Host2's error log when you run the first configuration, you might see a message about bind not working as it can not bind t 10.20.30.19 when it tries to bind the pong channel.

**Comment by daschgit** [comment]
Thanks a lot for the prompt reply Todd. In didn't realise that was a restriction, but in that case it makes perfect sense.

We, unfortunately, have a restriction in our network preventing me from initiating connections from host2 to host1, hence my attempt at the above.

On another somewhat related note regarding only being able to subscribe locally. Say you have a topology where Host1 is e.g. a market data publisher and you have many hosts wanting to subscribe to this data - and you don't know the list of hosts. I would normally have each host create a subscription pointing at Host1, but since that isn't possible would below be a good way to do it?

1. Host1 creates a subscriber on channel localhost:3456 listening for market data requests
2. HostX ... HostY creates a publisher with channel host1:3456 and sends a market data request
3. Host1 creates a new publisher for each market data request with channel HostX:1234 and publishes market data via all publishers.

Hope that makes sense?

Let me know if I should open a new question for this.

Once again, thanks a lot for your help!

**Comment by daschgit** [comment]
Hi Cesare,

Sorry, yes, I use UDP. I should have been more clear about the connection "initiation". We only have one-way host/ip mappings in our WAN, so we cannot point to host1 from host2, but I can work around this problem for now.

You are right, multicast would definitely be a better solution, especially with many subscribers. Great idea to use multiple groups to split by product.

Your help is much appreciated.

**Comment by cesaref** [comment]
Well in that case multicast looks like the best option, since the publish address is not related to the host interfaces, so as long as you can agree a multicast address mapping between the hosts, their actual interfaces aren’t important (just make sure on multi-homed hosts you publish to only the required interface).

Mapping multiple products to multicast groups is a tricky business - you have a limited IGMP membership on your switch, which will be something like 2,000 or so, therefore you can’t create a group per symbol unless you have a very limited set of symbols to distribute. I imagine you’ll need to understand the traffic shape broken down by symbol, and which hosts require which symbols before you can make a stab at an optimal solution, so just make sure you don’t bake in a single group into your aeron design, so that you have choices in the future.

One other thing, if you send to one group, the media driver will make more optimal use of the packet MTU, packing multiple messages into one network packet if your send rate is very high - you won’t be able to take advantage of this with multiple groups though.

**Comment by dasch-dk** [comment]
Brilliant, thanks for your input Cesare. Will definitely take all of the above into account when doing my design. We'll probably have a maximum of 200 subscribers so should be fine with the IGMP memberships. We do have a pretty good understanding of the traffic shape by symbol and will probably end up having single publishers (machines) for the very high throughput ones, so it is good to know that Aeron will give us even more benefit from this by optimally using the MTU.

**Comment by tmontgomery** [comment]
Another possibility would be Multi-Destination-Cast that we added not too long ago. What it allows is to have a Publication that can send to multiple Subscriptions like multicast, but with multiple unicasts instead. Take a look at the System Tests and the Wiki Channel Config Guide.

**Comment by dasch-dk** [comment]
Good tip Todd, that I hadn't seen before. Will definitely have a look at that.
Thanks both for your help and guidance - much appreciated.
