### ISSUE TITLE
What's the recommended way to determine how many data I can offer to a Publication?

### ISSUE THREAD

**Issue by bedding** [real-logic/aeron#406]
I have been using publication.poistionLimit() - publication.poistion() to determine how much space left before messages get backpressured. However, publication.poistionLimit() sometimes returns 0 even I never offer any data to the stream. I'm wondering if I have been abusing this helper function and if there is a better way to determine message backpressure before offering any data.

**Comment by tmontgomery** [comment]
Initially pub-lmt is 0 until a Subscription is connected.

Using pub-lmt can give you a sense of the amount of space.... but be aware that it is not guaranteed to always go forward (i.e. not go back). i.e. it is quite possible that the `positionLimit` might go backward from the time the method is called and an `offer`/`tryClaim` is performed. Unlikely, but flow control strategies (and congestion control strategies) are allowed to do that. In addition, if a Publication is shared, then other threads may be sending and eating into the limit at any time. And to make it more complicated, you could trip over the end of a term (`ADMIN_ACTION`) on a `offer`/`tryClaim` even if pub-lmt has room for a message.

Given these possibilities, using it as a guide is very rough. i.e. be aware that just because it says there is space, it may not be exact and it may change its mind or have other circumstances that would prevent publication from being successful.

The best way to consider it is how `select()` handles `FD_READ` and `FD_WRITE` as a hint and not a guarantee.

Is there a reason you need to know the amount of data before back pressure before you send?

**Comment by bedding** [comment]
Thank you for the quick reply!

The reason is that I need to send certain amount of fragments before the subscriber polls. I want to guarantee that these fragments are received as a whole by the subscriber, in another word, the subscriber get everything at a time or nothing. I don't want it to poll partial data and wait for the publisher to send more. The Publication is used only from a single thread.

An alternative way to solve my problem is letting the subscriber dismiss the partial data it received. But it would be more efficient to determine the size in advance.

**Comment by tmontgomery** [comment]
With flow control at the network level (not just pub-lmt), you can't be assured that a set of fragments will arrive together on the Receiver side nor that they will batch together. For IPC, you might be able to make this assumption, though. But I wouldn't.

This sounds like a transactional boundary. You can use something like `Image.controlledPeek` to see if everything is there or not to actually process. Saving data for processing in a single pass is not ideal, I know. But often necessary.
