### ISSUE TITLE
Questions about media driver warmup

### ISSUE THREAD

**Issue by bedding** [real-logic/aeron#434]
I was looking at Aeron-sample and found there are a couple of throughput tests that warm up media driver by sending and receiving 1,000,000 256 byte messages with a single stream. I have a few questions about warming up media driver, (for both IPC and UDP)

1. Does number of messages or total size of data matter when warming up media driver? Like, the difference between 1 million 256-bytes messages vs 1k 256KB messages?
2. Does number of streams matter when warming up media driver? Like, 1 stream with 1 million 256-bytes messages vs 10 streams concurrently with 100k 256-bytes messages? 
3. Whenever I added a new publication/subscription, namely a new stream, do I need to warm it up as well?
4. What is a recommended (message_count, message_size, stream_count) combination to warm up media driver?
5. I'm not very familiar with Java - why does the Java media driver need to be warmed up to achieve better performance?

**Comment by mjpt777** [comment]
The Java media driver needs to warm up so that the JIT compiler can kick in an compile the hot code. The C2 JIT compiler will need to see 10K+ observations of a method to consider it hot. This means that the size of the messages being less than or greater than the MTU will warm up different paths.

It is best to warm up with a realistic profile. Similar length messages and number of streams as this will give the JIT compiler better data to make its optimisation decisions.

Even our CPUs need to warm up these days with gathering data for branch prediction and priming caches, etc.
