### ISSUE TITLE
Question: Performance comparison with NORM protocol?

### ISSUE THREAD

**Issue by cspiker7** [real-logic/aeron#465]
I don't see a user forum for this project, so I will post my question as an issue. My apologies if there is a better place.

Has anybody has compared Aeron with the NORM protocol? 
https://www.nrl.navy.mil/itd/ncs/products/norm
They look similar and I'm trying to understand improvements Aeron might have included over the open-source NORM. The specification mentions that much of the same design was used.

**Comment by tmontgomery** [comment]
I've not heard of a comparison of the implementations.

Several of the concepts present in the NORM protocol are used. As is the case for any NAK oriented protocol, actually, since NORM incorporates the best known techniques. Several specifics are different, but the basics of NAK operation haven't drastically changed from SRM semantics. http://www.icir.org/floyd/srm.html

From an implementation standpoint, the design of Aeron is very very different than the NORM implementation. Especially related to throughput and latency.
