### ISSUE TITLE
Cyclic dependency between Aeron packages

### ISSUE THREAD

**Issue by exercitussolus** [real-logic/Aeron#47]
There appears to be a cyclic dependency between packages uk.co.real_logic.aeron.driver and uk.co.real_logic.aeron.driver.cmd. Not sure if this is an issue, but it surely breaks the acyclic dependencies principle as formulated by Robert C. Martin in  his seminal work "Agile Software Development, Principles, Patterns, and Practices". See the pic below, obtained by an automated ( scripted ) package dependency detection with Sparx Enterprise Architect, after having reverse-engineered Aeron into it. 

![aeron_package_deps](https://cloud.githubusercontent.com/assets/2629689/5592405/b17b88c8-91cd-11e4-8873-b1ac1c891431.jpg)

**Comment by mjpt777** [comment]
I agree in general that circular dependencies can be troublesome. In this case it happens because the command objects have been pulled out into a sub-package for clarity. The relationships are valid and could only be broken by adding lots of interfaces that would increase complexity for no return.

If you know of a better way to semantically identify a group of classes in Java that are really part of a package I'd be interested to know about it.
