### ISSUE TITLE
Expose fd in client for use with epoll

### ISSUE THREAD

**Issue by lukepalmer** [real-logic/aeron#533]
We're in an environment with a bunch of data sources, almost all of which use epoll in order to know when to wake up. 

In order to get the best latency in an Aeron client we have to busy spin. That unfortunately negatively impacts everything else that wants to use epoll.

Would it be possible to expose a file descriptor in the client (possibly to the mmaped image?) that would allow an aeron client to get plugged in to epoll and play nice in a more diverse environment?

Thoughts much appreciated!

**Comment by cesaref** [comment]
It sounds to me like you have core contention on your host, as otherwise I can't see why aeron spinning would adversely affect the latency of other processes running on the host (epolling or not).

Assuming you do have core contention, then i'd suggest re-evaluating whether the hardware has the capacity you need for the latency you are wanting to achieve. You can use csets to provide dedicated cores for the media driver, and consider moving to 1 core rather than 3 for the media driver to partition the hardware resources more appropriately.

Another thing to consider would be alternative network hardware with kernel bypass drivers, which has the advantage of reduced context switches and interrupts, lower CPU use, lower latency, and dedicated ports for the aeron traffic.

**Comment by lukepalmer** [comment]
Thanks for the reply. I probably didn't explain well. I have a single-threaded process that gets other data via epoll that I also want to use aeron with. It does work if I'm smart about polling, but was wondering about the possibility of getting everything into epoll.

**Comment by tmontgomery** [comment]
Wrapping a client agent invoker + polling mechanism into a duty cycle that also calls epoll for a set of FDs is not too hard to do and can be quite efficient. Instead of having Aeron indicate data by triggering an FD, you can simply call Subscription::poll and the client agent invoker from your duty cycle. i.e. instead of waiting on epoll, poll it, then poll Aeorn and agent invoker, and then if no work to do, use an idle strategy with a backoff. It's essentially what epoll does anyway in many cases with active FDs.

**Comment by mjpt777** [comment]
Another option to consider is is to put the connections into non-blocking mode and busy poll everything.

**Comment by lukepalmer** [comment]
Agree that I can do this as you've suggested- closing.
