### ISSUE TITLE
Cluster node fails to start due to unknown recording id=-1

### ISSUE THREAD

**Issue by zyulyaev** [real-logic/aeron#604]
Steps to reproduce:
1. Configure 3 node cluster;
2. Start all 3 nodes;
3. Send SHUTDOWN command via ClusterControl;
4. Start all 3 nodes;
5. Send SHUTDOWN command;
6. Clear recording log of one of the nodes;
7. Start all 3 nodes - the node without recording log will shutdown;
8. Start the down node - it will shutdown again;
9. Start the down node - it will throw ArchiveException.

The down node after 8th step will contain a snapshot entry with recordingId=-1 in the recording log.
The entry is added to the log because ConsensusModuleAgent processes SHUTDOWN action during replay, while ClusteredServiceAgent does not. So when ConsensusModuleAgent waits for an ack on SHUTDOWN action, ClusteredServiceAgent actually sends an ack on replay complete which does not contain recordingId.

**Comment by tmontgomery** [comment]
Step 6 creates something we don't support. i.e. a cluster member that is out of step in terms of state. i.e. no snapshot from the previous shutdown.

I can't quite seem to reproduce this without that step, though. Can you check to see if without that step you can get this to occur?

**Comment by zyulyaev** [comment]
> Step 6 creates something we don't support.

I was afraid of that. But how is it supposed to handle situations where no recording log is available, like if the disk is corrupted?

> Since the shutdown takes a snapshot, it needs to execute it while catching up. And that will terminate the node.

Is it intended behaviour? It looks quite weird to me actually :smile:

> Can you check to see if without that step you can get this to occur?

I would expect following scenario to do the same thing, but it does not:
1. Configure 3 node cluster;
2. Start all 3 nodes;
3. Send SHUTDOWN command via ClusterControl;
4. Start all 3 nodes;
5. Stop one of the nodes.
6. Send SHUTDOWN command;
7. Start all 3 nodes - the previously stopped node will shutdown;
8. Start the down node.

**Comment by zyulyaev** [comment]
I found out that cluster may start with only majority of nodes, so I know how to reproduce this without deleting recoding.log:
1. Configure 3 node cluster.
2. Start nodes 1 and 2 and wait for cluster to start.
3. Send SHUTDOWN command via ClusterControl;
4. Start nodes 1 and 2 and wait for cluster to start.
5. Send SHUTDOWN command;
6. Start all 3 nodes - 3rd node will shutdown.
7. Start 3rd node - it will shutdown again.
8. Start 3rd node - it will throw ArchiveException.

**Comment by tmontgomery** [comment]
I misspoke. Step 6 actually is supported. Just not ideal. The behavior is that the member will try to replay the log. If the leader doesn't have it (such as if during the shutdown, the leader got rid of anything earlier than the snapshot), the member will not be able to catchup. So, blowing away the log on one member is not advised unless the other members can replay from position 0. Which in this case it was. Just not obvious with the snapshots in the shutdown.

The issue is that somehow the snapshot recording in the snapshot is not being handled properly and after a while it figures this out.

However, it opens an issue I am trying to figure out a better solution to. The shutdown creates a snapshot that must be performed during the catchup. That snapshot when doing a catchup is executed. But it also executes the shutdown attached to it. Causing the node to stop. Because the shutdown is coupled to the snapshot. So, trying to figure out if separating the actions is necessary or we have to create complexity to execute the snapshot but not the shutdown. And in that case, need to find the right indicator that the shutdown should not be done.... it's not simple as the shutdown could be initiated during a catchup and timing might make it so that the node performing doesn't shutdown.... which would cause an election, etc.

**Comment by tmontgomery** [comment]
I'm in the middle of changing this. The shutdown will be separated from the snapshot. SHUTDOWN and ABORT will no longer be events in the log. Same functionality, but a SHUTDOWN for the control toggle will trigger and snapshot and a termination coordination with the followers and their services. An ABORT will simply cause a coordinated termination without a snapshot being taken. This means that a replay will not have to deal with a shutdown or abort event.

**Comment by zyulyaev** [comment]
Sounds great! I tried to use ABORT command and it looked broken as well. Follower nodes would shutdown on every replay after that command. I was not sure if it is related to this issue though.

**Comment by tmontgomery** [comment]
In a situation where a node was catching up, it needed to execute the log. Since SHUTDOWN and ABORT were events in the log, they needed to be executed. That is no longer the case.

**Comment by zyulyaev** [comment]
Is it fixed in 1.14.0?

**Comment by mjpt777** [comment]
Yes.
