### ISSUE TITLE
Performance issue in udp socket read

### ISSUE THREAD

**Issue by vad0** [real-logic/aeron#804]
As far as I see in profile, Aeron uses DatagramCahnnelImpl::receive method to read from UDP socket. It uses lock, SecurityManager and a lot of logic. One can also see that Chronicle implementation does much less stuff and is a little bit more performant. It would be good to see a custom implementation of udp socket read which does as little as possible, but not less.

**Comment by tmontgomery** [comment]
We are more than acutely aware of the limitations on `DatagramChannelImpl.receive`. In fact, we go out of our way to stay on the right side of bias locking. Also, for the Sender path (high throughput path), we use connected sockets to avoid the SecurityManager as much as possible.

Beyond this, though, the `receive` call actually allocates in some common situations (http://mail.openjdk.java.net/pipermail/nio-dev/2018-August/005384.html). And for high rate, the lack of access to `recvmmsg` means more crossings of the kernel boundary than is desirable.

Going forward, there is only so much that the Java driver can do for us due to the state of NIO. The C native driver already does a lot of what is needed and does it quite well (`recvmmsg/sendmmsg`, allowing for ef_vi/DPDK/io-uring integration, and allowing for an efficient security implementation).

**Comment by vad0** [comment]
But you don't have to use DatagramChannelImpl::receive at all. You can use a custom implementation like the one on . second 27:45 here: https://www.youtube.com/watch?v=QV-ue1YMdds&list=PLVe-2wcL84b_ZJJywYZru7IQVvIPcfj6a&index=27&t=0s

**Comment by tmontgomery** [comment]
Or as I mentioned, we can utilize the C native driver where we can go fully in the directions we plan to take Aeron.

**Comment by vad0** [comment]
OK, understood.

**Comment by mjpt777** [comment]
A lock is not used when biased locking is enabled. We are very careful to not have the biased lock revoked by using he channel across threads.
